/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ViewSlugRouteImport } from './routes/view.$slug'
import { Route as AuthenticatedBroadcastSlugRouteImport } from './routes/_authenticated/broadcast.$slug'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ViewSlugRoute = ViewSlugRouteImport.update({
  id: '/view/$slug',
  path: '/view/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBroadcastSlugRoute =
  AuthenticatedBroadcastSlugRouteImport.update({
    id: '/broadcast/$slug',
    path: '/broadcast/$slug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/view/$slug': typeof ViewSlugRoute
  '/broadcast/$slug': typeof AuthenticatedBroadcastSlugRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/view/$slug': typeof ViewSlugRoute
  '/': typeof AuthenticatedIndexRoute
  '/broadcast/$slug': typeof AuthenticatedBroadcastSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/view/$slug': typeof ViewSlugRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/broadcast/$slug': typeof AuthenticatedBroadcastSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/view/$slug' | '/broadcast/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/view/$slug' | '/' | '/broadcast/$slug'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/view/$slug'
    | '/_authenticated/'
    | '/_authenticated/broadcast/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ViewSlugRoute: typeof ViewSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/view/$slug': {
      id: '/view/$slug'
      path: '/view/$slug'
      fullPath: '/view/$slug'
      preLoaderRoute: typeof ViewSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/broadcast/$slug': {
      id: '/_authenticated/broadcast/$slug'
      path: '/broadcast/$slug'
      fullPath: '/broadcast/$slug'
      preLoaderRoute: typeof AuthenticatedBroadcastSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedBroadcastSlugRoute: typeof AuthenticatedBroadcastSlugRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedBroadcastSlugRoute: AuthenticatedBroadcastSlugRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ViewSlugRoute: ViewSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
